### ISSUE TITLE
android上的packflutter.gradle能用吗？

### ISSUE THREAD

**Issue by TinoGuo** [Sum-sdl/FlutterSimpleDemo#1]
RT.
能正常打包出aar吗？

**Comment by yinhaijiao** [comment]
@TinoGuo 你成功了吗？可以分享下么？为什么我打的时候就提示android下面缺少packflutter呢？

**Comment by TinoGuo** [comment]
@yinhaijiao 没成功，而且后面官方更新了脚本，都可以合进去了，我目前用官方的办法
